<?php
use Solid\Repositories\MigrationRepository;
use Solid\Collections\Migration;

/**
 * Created by ICOM-CMS
 * User: kiendt
 * From cms cli
 */
class migrationController extends MY_Controller
{
	/**
     * @var MigrationRepository $migrationRepository
     */
    private $migrationRepository;

	public function __construct(MigrationRepository $migrationRepository)
	{
		parent::__construct();
		//load model
        $this->load->model('$Migration_model','migrationModel');

        //dependencies injection
        $this->migrationRepository = $migrationRepository;
        $this->migrationRepository->setModel($this->migrationModel);
	}

	public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    public function after()
    {
        parent::after(); // TODO: Change the autogenerated stub
    }
}